pool:
  vmImage: ubuntu-18.04

variables:
  - group: pipeline-secrets
  - name: version
    value: 2.1.7-assentis-2 # Carefully review before PR

trigger:
  branches:
    include:
      - master

steps:
  # branch builds are doing branch specific SNAPSHOT
- template: templates/maven.yml
  parameters:
    displayName: branch build
    revision: $(version)-$(Build.SourceBranchName)-SNAPSHOT
    goals: deploy
    condition: and(not(startsWith(variables['Build.SourceBranch'], 'refs/pull')), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

  # pull request builds are executing only the install maven goal
- template: templates/maven.yml
  parameters:
    displayName: pullrequest build
    revision: $(version)-SNAPSHOT
    condition: startsWith(variables['Build.SourceBranch'], 'refs/pull')

  # master build is doing a release (no SNAPSHOT set). This requires to properly update the version 
  # in this pipeline step each time one wants to do a release...
- template: templates/maven.yml
  parameters:
    displayName: release build
    revision: $(version)
    goals: deploy
    profiles: azure,release
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')